version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ahmed
      MYSQL_PASSWORD: mysqlpassword
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql 

  backend:
    build: 
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:mysql@localhost:3306/ecommerce
    volumes:
      - ./src:/app/src:ro
    ports:
      - "3001:3001"
    command: "npm run start:dev"

volumes:
  mysql-data: